project_id = "pqttoyjfilclrxtjoikk"

[functions.transcribe-audio]
verify_jwt = false

[functions.generate-soap-notes]
verify_jwt = false

[functions.transcribe-assemblyai]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false
